doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        charset: UTF8
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Photo:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Photo/Entity'
                prefix: 'App\Photo\Entity'
                alias: Photo
            Auth:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: Auth
            Like:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Like/Entity'
                prefix: 'App\Like\Entity'
                alias: Like
